# Generated by Django 3.2.3 on 2021-06-30 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idpais',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Pais')),
                ('nombrepais', models.CharField(max_length=50, verbose_name='Nombre del pais')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('NombreCompleto', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('Telefono', models.CharField(max_length=30, verbose_name='Telefono')),
                ('Rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='RUT')),
                ('correo', models.EmailField(max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuario')),
                ('Direccion', models.CharField(max_length=100, verbose_name='Direccion')),
                ('Pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.idpais')),
            ],
        ),
    ]
